#!/bin/sh
# ╔══════════════════════════════════════════════════════════════════════╗
# ║  Star-Talk / 星语 — RootFS Assembly                               ║
# ║  Finalizes the root filesystem staging area                        ║
# ╚══════════════════════════════════════════════════════════════════════╝
set -e
. "$(dirname "$0")/utils-netbsd.sh"

PHASE="N05"
START_TIME=$(date +%s)
step "Phase ${PHASE}: Assembling root filesystem"

# ── Ensure essential directories exist ────────────────────────────────
step "Creating filesystem structure..."
for d in dev proc sys tmp var/log var/run var/db var/spool \
         mnt media boot home root rescue opt bin sbin lib libexec \
         usr/local/bin usr/local/sbin usr/local/etc usr/local/lib \
         usr/local/share usr/pkg usr/share usr/libdata; do
    mkdir -p "$ROOTFS_DIR/$d"
done

# ── Symlinks for usr-merge compatibility ──────────────────────────────
for d in bin sbin lib libexec; do
    if [ ! -L "$ROOTFS_DIR/$d" ] && [ ! -d "$ROOTFS_DIR/$d/." ]; then
        ln -sf "usr/$d" "$ROOTFS_DIR/$d" 2>/dev/null || true
    fi
done

# ── Standard device nodes ─────────────────────────────────────────────
step "Creating essential device nodes..."
if [ ! -e "$ROOTFS_DIR/dev/console" ]; then
    (cd "$ROOTFS_DIR/dev" && {
        mknod console c 0 0 2>/dev/null || true
        mknod null c 2 2 2>/dev/null || true
        mknod zero c 2 12 2>/dev/null || true
        mknod tty c 1 0 2>/dev/null || true
        mknod klog c 7 0 2>/dev/null || true
    })
fi
success "Device nodes created"

# ── Create /etc files ─────────────────────────────────────────────────
step "Creating system configuration files..."

# hostname
echo "startalk" > "$ROOTFS_DIR/etc/myname"
echo "startalk" > "$ROOTFS_DIR/etc/hostname"

# resolv.conf placeholder
cat > "$ROOTFS_DIR/etc/resolv.conf" << DNS
# Generated by dhcpcd
nameserver 8.8.8.8
nameserver 1.1.1.1
DNS

# Shell configuration
cat > "$ROOTFS_DIR/etc/shells" << SHELLS
/bin/sh
/bin/csh
/bin/ksh
/usr/pkg/bin/bash
SHELLS

# locale config
mkdir -p "$ROOTFS_DIR/etc"
cat > "$ROOTFS_DIR/etc/locale.conf" << LOCALE
LANG=zh_CN.UTF-8
LC_CTYPE=zh_CN.UTF-8
LC_COLLATE=zh_CN.UTF-8
LC_TIME=zh_CN.UTF-8
LC_NUMERIC=zh_CN.UTF-8
LC_MONETARY=zh_CN.UTF-8
LC_MESSAGES=zh_CN.UTF-8
LOCALE

# ── Create default user ───────────────────────────────────────────────
step "Creating default user 'startalk'..."
if [ -f "$ROOTFS_DIR/usr/sbin/useradd" ]; then
    # Not running on real root — we need master.passwd approach
    info "User will be created on first boot"
else
    info "User 'startalk' will be created by post-install script"
fi

# ── Set permissions ───────────────────────────────────────────────────
step "Setting permissions..."
find "$ROOTFS_DIR/etc/rc.d" -type f -exec chmod 755 {} \; 2>/dev/null || true
chmod 755 "$ROOTFS_DIR/usr/local/sbin/"* 2>/dev/null || true

# ── Rootfs size summary ───────────────────────────────────────────────
info "Root filesystem size: $(du -sh "$ROOTFS_DIR" 2>/dev/null | cut -f1 || echo 'unknown')"
info "Top-level directories:"
du -sh "$ROOTFS_DIR"/*/ 2>/dev/null | sort -rh | head -8 || true

cd "$PROJECT_ROOT"
build_summary "$PHASE" "$START_TIME"
